<?php
/**
 * WppconnectApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingster
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ~ PINGSTER ~
 *
 * Dokumentasi API Pingster
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Pingster\Test\Api;

use \Pingster\Configuration;
use \Pingster\ApiException;
use \Pingster\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WppconnectApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pingster
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WppconnectApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for wppconnectControllerCheckSessionStatus
     *
     * .
     *
     */
    public function testWppconnectControllerCheckSessionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wppconnectControllerCreateSession
     *
     * .
     *
     */
    public function testWppconnectControllerCreateSession()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wppconnectControllerGetQRCode
     *
     * .
     *
     */
    public function testWppconnectControllerGetQRCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wppconnectControllerLogout
     *
     * .
     *
     */
    public function testWppconnectControllerLogout()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for wppconnectControllerSendMessage
     *
     * .
     *
     */
    public function testWppconnectControllerSendMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
